# Generated by Django 5.1.3 on 2024-12-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
