# Generated by Django 5.1.3 on 2024-12-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', help_text='Enter your name', max_length=120, verbose_name='Name')),
                ('email', models.EmailField(blank=True, default='', help_text='Enter your email address', max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, default='', help_text='Enter your subject', max_length=120, verbose_name='Subject')),
                ('message', models.TextField(blank=True, default='', help_text='Enter your message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['name'],
            },
        ),
    ]
